name: ContextKeyV2
options:
  bundleIdPrefix: com.nativerse.contextkey
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.4"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: YES

targets:
  ContextKeyV2:
    type: application
    platform: iOS
    sources:
      - ContextKeyV2
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSFaceIDUsageDescription: "ContextKey uses Face ID to protect your personal context data."
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "ContextKey uses speech recognition to transcribe your voice notes on-device."
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "ContextKey needs microphone access to record voice notes for context extraction."
        PRODUCT_BUNDLE_IDENTIFIER: com.nativerse.contextkey.v2
    resources:
      - ContextKeyV2/Assets.xcassets

  ContextKeyV2Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ContextKeyV2Tests
    dependencies:
      - target: ContextKeyV2
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nativerse.contextkey.v2.tests
